### ISSUE TITLE
Ping / Latency info

### ISSUE THREAD

**Issue by HanFox** [Zyin055/zyinhud#30]
Is it possible to get ping/latency to a server for display? I'm not sure if MC even really handles it as a number internally.

If not, that's fine, but it'd be much more useful to get an actual onscreen figure instead of just a useless image on the TAB screen.

**Comment by Zyin055** [comment]
Getting your ping in Minecraft is not a trivial task. In my opinion the tab display does a good enough job to not warrant the effort of coding this up because it would be sort of difficult.

For future reference, the bars on the tab list represent a ping of 1000-600-300-150-0ms.

**Comment by HanFox** [comment]
Shame, but I guessed as much.

Sadly supplying those figures is still pretty useless for actually figuring out your ping.

Thanks anyway.
