### ISSUE TITLE
‘Eating aid’ doesn't work with re-bound keys

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Zyin055/zyinhud#32]
I've my left-click set to place, and right-click set to dig (this makes way more sense to me than having to use the *alternate* click to place blocks in a game about placing blocks.)

Unfortunately, this apparently breaks the ‘eating aid’ `G` key? Instead of eating, it tries to automatically break the block in front of me … using a steak. Not very effective. :P

**Comment by Zyin055** [comment]
Due to how Eating Aid works and the restrictions of being a client side mod, this functionality won't be changing. I looked into it back when I was making Torch Aid work with rebound hotkeys. Sorry but it'll only work with right click.

**Comment by ELLIOTTCABLE** [comment]
This is strange, as torch aid *does* work for me. At least, as far as I can tell?

**Comment by Zyin055** [comment]
Torch Aid does work with rebound hotkeys. Eating Aid does not. It would be a challenge to get Eating Aid to work with rebound hotkeys and it's not something that I'm willing to put time into considering the vast majority of players use the default right click hotkey.

**Comment by ELLIOTTCABLE** [comment]
Ah, I see.

(Related: At the very least, I'd like to point out that *every single player* I know with a touchpad plays with either E and Q, or Q and E, replacing left and right click. None of them press to mine. I suspect that's a *large* minority of players. Perhaps poll in your forum thread to see if it'd be worth the work to your other users? :x)

Anyway. Thanks for the quick replies, either way. <3

**Comment by Starwort** [comment]
I accidentally made my own duplicate of this, and _**I USE LEFT CLICK TO USE/PLACE TOO!!!!!**_
