### ISSUE TITLE
Dynamic hotkey-reference on the ⌃⌥Z screen

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Zyin055/zyinhud#33]
I've always gotta dig through the Zyin settings to find the hotkeys, which I can never remember. The control-option-Z screen is so nearby; it'd be wonderful to see a hotkey reference in the background of that screen (of course, preferably showing whatever you have changed the hotkeys to, instead of the defaults … but I'll take what I can get.)

**Comment by Zyin055** [comment]
That's a good idea, I'll see what I can do.

**Comment by Zyin055** [comment]
Is this what you were thinking of?

http://i.imgur.com/ihlofIn.jpg

**Comment by ELLIOTTCABLE** [comment]
Oh, wow, I love that. Way better than what I was picturing.

:shipit:

**Comment by Zyin055** [comment]
Added in v.1.4.1
