### ISSUE TITLE
Durability info gives Xray

### ISSUE THREAD

**Issue by Risk77** [Zyin055/zyinhud#36]
I'm running Minecraft 1.8 with forge 11.14.0.1289 and OptiFine 1.8 HD U C2
Zyin's Hud 1.4.0
When the durability info displays me the little warning box, it gives a Xray, where you can see every caves around you.
Tried without optifine. Same result.
![1](https://cloud.githubusercontent.com/assets/11005315/6199582/cefd4b7e-b44c-11e4-87f6-671e246a2ae5.jpg)

**Comment by Zyin055** [comment]
I tried this with Forge 1289 and 1299 (latest recommended) versions and could not replicate this. I was using a completely vanilla environment with no other mods.
Based on your screenshot it looks like the textures are cut and are randomly becoming transparent which I have never seen before. Perhaps this is an issue with your Java install or texture pack? I have no clue.

**Comment by Risk77** [comment]
I have Java 7 update 71 (64 bits)
My ressource pack is faithful 32x32 but it does the same without any one.
Tried to take off every other mods but same problem.
Here's my debug info : https://app.box.com/s/13xj3ucmaiipbho07gez6p7e7dh2ah4l
I have nothing in console.
Maybe it's my Java version, but it's strange

**Comment by Zyin055** [comment]
Were you able to fix your issue?

**Comment by Risk77** [comment]
I've both tried on Java versions 7 & 8 and couldn't fix it in any ways.
My last thought is that maybe my graphic card does not like it.

**Comment by HeroCC** [comment]
You can click the close button if there is no longer a problem, glad you fixed it!
