### ISSUE TITLE
FATAL Exception - don't know how to reproduce

### ISSUE THREAD

**Issue by kreezxil** [Zyin055/zyinhud#39]
crash report: http://paste.ee/p/KGbnt
fml client latest: http://paste.ee/p/ywpYp

**Comment by kreezxil** [comment]
I just reproduced it, something is happening to the torch placer function.
Just placed on on snow and it crashed the client
crash report: http://paste.ee/p/2FshX

**Comment by Zyin055** [comment]
Those logs you posted don't contain a crash report. I am also unable to reproduce your error when trying to place a torch on a 1 high snow layer block while using Torch Aid. In order for me to investigate this I'll need to have detailed steps to reproduce it as well as your Forge version.

**Comment by kreezxil** [comment]
Crash Reports:

http://paste.ee/p/RcZPO
http://paste.ee/p/1Croi

I'll keep monitoring it to hopefully develop steps to reproduce it.

Forge: 11.14.1.1332

**Comment by kreezxil** [comment]
I got another FATAL crash. Was running around and decided to whip up a furnace right quick, plopped it down and immediately right clicked it, crash!

multimc log: http://paste.ee/p/G6iji
mmc crash report: http://paste.ee/p/ZgHfn
mmc fml client latest: http://paste.ee/p/St7sM

**Comment by Zyin055** [comment]
Do you have any mods that change the size of the player's inventory or alter it in any way? I still can't figure out what is causing the crash to occur based on the crash report. I will add in a temporary fix to make sure it won't crash the game in future versions (v.1.4.2+).

**Comment by kreezxil** [comment]
There's baubles which adds 4 new slots and inventory tweaks which gives new
functions to managing the player inventory. Inventory tweaks tries to
automatically replace destroyed tools as well. Mouse tweaks also adds even
more functionality to player inventory. Portable crafting bench which can
pull items out of your inventory into it's grid when you hit the "?" in the
NEI. Hopefully one of those is the problem and we can single this out.

Baubles <http://minecraft.curseforge.com/mc-mods/227083-baubles>
Inventory Tweaks
<http://minecraft.curseforge.com/mc-mods/223094-inventory-tweaks>
Mouse Tweaks <http://minecraft.curseforge.com/mc-mods/60089-mouse-tweaks>
Portable Crafting Bench
<http://minecraft.curseforge.com/mc-mods/227547-portable-craft-bench>

My full modpack list always at 1.8 Forge Mods List | KreezCraft
<http://kreezcraft.com/1-8-forge-mods-list/>
