### ISSUE TITLE
Index Out of Bounds

### ISSUE THREAD

**Issue by kreezxil** [Zyin055/zyinhud#40]
client crash report: http://paste.ee/p/uhYWm
fml client latest: https://paste.ee/p/ZoK6X

**Comment by kreezxil** [comment]
Got another one:

fml latest log: https://paste.ee/p/sL6OG
crash report: https://paste.ee/p/qefNK

**Comment by HeroCC** [comment]
Just so you know, you already have another issue #39. It seems they are the same issue, so you may want to keep all information. If you are sure the issues are COMPLETELY different, then let us know.

**Comment by kreezxil** [comment]
I know it's a duplicate issue. But the instance is newer. Meaning it's still happening. It is my intention that you might notice a pattern in them and be able to create a patch.

-----Original Message-----
