### ISSUE TITLE
CI Available

### ISSUE THREAD

**Issue by JamieSinn** [Zyin055/zyinhud#43]
Hey,

If you'd like, I can set up CI for your mod on my jenkins server: http://ci.sinndevelopment.com

I wish GH had a private message feature.

**Comment by Zyin055** [comment]
I don't know what CI is or what a jenkins server is. Can you explain?

**Comment by JamieSinn** [comment]
CI is continuous integration, for you, this means every github commit pushed you will have a build available. 
Jenkins is the most popular ci server right now. 

Basically it allows you to always have builds available.

**Comment by Zyin055** [comment]
I still don't quite understand the benefit for having CI. Can you give me a common use case for a user? How is it different than the user downloading and installing the .jar from CurseForge?

Also I usually do commits for each version update (I know that's not how you're supposed to use commits but whatever) so there'd be no benefit to having a dev build available at all times.

**Comment by JamieSinn** [comment]
As you don't use the commits for the common use :P it's mostly useless but always there if you'd like it.
The only thing I could think of, would be not needing to change the curse download as you can use the lastBuild arg with jenkins to grab the latest build.
