### ISSUE TITLE
Client freezes entirely when attempting to Quick Deposit into an AE2 access terminal

### ISSUE THREAD

**Issue by BBoldt** [Zyin055/zyinhud#44]
![](http://i.imgur.com/5QwtQ1n.png)

* appliedenergistics2-rv2-stable-10
* ZyinsHUD-(1.7.10)-v.1.3.9

Nothing showed up in the logs, it just stopped completely.

**Comment by esotericist** [comment]
This occurs not just with AE2, but with many large inventories. (see: Binnie's Mods Compartments, Magneticraft shelving unit, even large Iron Chest containers or Enhanced Inventories containers)

The most common pattern I've seen is the combination of target inventory having significantly more of a thing than can fit in your inventory, and having a lot of that thing in your inventory when attempting to quick deposit. But it also seems to more rarely happen under less clear circumstances, like a half-full inventory into a chest-sized non-vanilla container with only one stack in it.

Sadly for us, dev has reported there will be no further updates for 1.7.10.

**Comment by Zyin055** [comment]
I've noticed this happen too with AE2 too in the past. At that time I looked into it and couldn't figure out why it was happening and still don't today. I think for 1.8 I try to catch all exceptions to possibly prevent it but obviously can't test it since AE2 is 1.7.10 only.
