### ISSUE TITLE
Barrier Block Safe Overlay broken

### ISSUE THREAD

**Issue by HeroCC** [Zyin055/zyinhud#47]
If you place barrier blocks on the ground and the safe overlay is on, they will still show up even though they can't spawn mobs there. Included is a picture.
![2015-11-06_20 00 50](https://cloud.githubusercontent.com/assets/2124489/11012395/5e0046b0-84c1-11e5-8c69-1247e8a8a20d.png)
Thanks! I can provide more info if needed.

**Comment by Zyin055** [comment]
It'll be fixed in 1.4.6
