### ISSUE TITLE
Negative coordinates off by 1

### ISSUE THREAD

**Issue by lfudala** [Zyin055/zyinhud#48]
Coordinates for both x and z on the negative side of zero are off by 1. Going from 0 on the x or z axis in the negative direction, the coordinates start counting from 0 again instead of moving to -1.

on x=0
move 1 block west
game reports x as -1, coordinates in hud are reported as x=0

**Comment by Zyin055** [comment]
These is because of rounding. Either we skip a number or round it up or down. I chose to round it down.

This is its current behavior:

F3 menu -> Info Line
-1.5 -> -2
-0.5 -> -1
0.5 -> 0
1.5 -> 1
