### ISSUE TITLE
torch aid causes issues with shift-rightclick

### ISSUE THREAD

**Issue by 4rz0** [Zyin055/zyinhud#50]
While experimenting with 1.8.8 mods, I also notice a problem with the torch aid.
Certain machines (I'm sure there are a few out there) require to be shift-rightclicked to access a certain function.
In my case it's Storage Drawers, where I can access the upgrade slots trough that.
When I do that with torch aid activated, instead of accessing the slots, I place down a torch.
Now I don't know if this is the HUD's fault or a problem with the implementation of the drawer's access.
I can't test that with other mods, since there are no other out there that can be used like that at this time.
Either way, I suggest adding the possibility to deactivate certain functionality of torch aid, like placing torches with empty hands.

Everyone likes config options ;D

**Comment by Zyin055** [comment]
Torch Aid has has many issues. The main issue is that this mod is 100% client side, and the client doesn't know which blocks are right-clickable without actually executing the code which performs that blocks right click function. Seeing as how many modded blocks require the use of an empty hand, I may simply stop Torch Aid from functioning with an empty hand. I don't think this should be yet another config option.

**Comment by 4rz0** [comment]
Yea, that would work as well.

**Comment by Zyin055** [comment]
Implemented in 1.4.8.
