### ISSUE TITLE
1.12.2? I can't seem to find it, where is it?

### ISSUE THREAD

**Issue by AlsoShy** [Zyin055/zyinhud#67]
Tittle

**Comment by Zyin055** [comment]
Gotta be more descriptive than that, buddy. This repo hasn't been updated in 8 years.

**Comment by AlsoShy** [comment]
then where can I find the 1.12.2 port?
or can you update it, if not
Ima port it

**Comment by Zyin055** [comment]
This repo is dead, a 1.12.2 version doesn't exist.

**Comment by AlsoShy** [comment]
Why is it dead? can you please port it to 1.12.2.
alot of people would like it

**Comment by HeroCC** [comment]
There's a fork with a 1.12.2 version here https://github.com/cyilin/zyinhud/releases/tag/ZyinsHUD-1.12-1.5.5.18
